[ci]
verbosity = 4

[default]
src = 'contracts'
test = 'fuzzing'
out = 'out'
libs = ['lib']
remappings = []
allow_paths = []
libraries = []
cache = true
cache_path = 'cache_foundry'
# Whether to ignore the cache
force = false
auto_detect_solc = false
evm_version = 'london'
solc_version = '0.8.0'
offline = true
optimizer = true
optimizer_runs = 1
verbosity = 0
ignored_error_codes = []
fuzz_runs = 256
fuzz_max_local_rejects = 65536
fuzz_max_global_rejects = 102400
ffi = false
sender = '0x00a329c0648769a73afac7f9381e08fb43dbea72'
tx_origin = '0x00a329c0648769a73afac7f9381e08fb43dbea72'
initial_balance = '0xffffffffffffffffffffffff'
block_number = 1
chain_id = 31337
gas_limit = 9223372036854775807
gas_price = 0
block_base_fee_per_gas = 0
block_coinbase = '0x0000000000000000000000000000000000000000'
block_timestamp = 1
block_difficulty = 0
gas_reports = ["*"]
no_storage_caching = false
rpc_storage_caching = { chains = "all", endpoints = "remote" }
extra_output = []
extra_output_files = []
bytecode_hash = "ipfs"
sparse_mode = false
via_ir = false
revert_strings = "default"
# Switch optimizer components on or off in detail
#optimizer_details = None
# Url of the rpc server that should be used for any rpc calls
#eth_rpc_url = None
# Etherscan API key
#etherscan_api_key = None
# Only run test functions matching the specified regex pattern
#test_pattern= None
# Only run test functions that do not match the specified regex pattern
#test_pattern_inverse = None
# Only run tests in contracts matching the specified regex pattern
#contract_pattern = None
# Only run tests in contracts that do not match the specified regex pattern
#contract_pattern_inverse = None
# Only run tests in source files matching the specified glob pattern
#path_pattern = None
# Only run tests in source files that do not match the specified glob pattern
#path_pattern_inverse = None
# The block gas limit
#block_gas_limit = None
memory_limit = 33554432000
names = true
sizes = true
tab_spaces = 2
